// <auto-generated />
using System;
using AddressMicroservice.Etities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressMicroservice.Migrations
{
    [DbContext(typeof(AddressContext))]
    partial class AddressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("AddressMicroservice.Etities.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            CityID = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            CityName = "Veternik",
                            CountryID = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f"),
                            CountryName = "Srbija",
                            Number = 89,
                            Street = "Devet Jugovica",
                            ZipCode = "21203"
                        },
                        new
                        {
                            AddressID = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            CityID = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            CityName = "Veternik",
                            CountryID = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f"),
                            CountryName = "Srbija",
                            Number = 2,
                            Street = "Svetozara Miletica",
                            ZipCode = "21203"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
