// <auto-generated />
using System;
using DocumentMicroservice.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocumentMicroservice.Migrations
{
    [DbContext(typeof(DocumentContext))]
    partial class DocumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentMicroservice.Entities.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DocumentDate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("DocumentName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvarchar(250)");

                    b.Property<int>("DocumentSerialNumber")
                        .HasColumnType("int")
                        .HasColumnName("int");

                    b.Property<DateTime>("DocumentSubmissionDate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("DocumentTemplate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvarchar(250)");

                    b.Property<Guid>("ListOfDocumentsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId");

                    b.HasIndex("ListOfDocumentsID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DocumentMicroservice.Entities.ListOfDocuments", b =>
                {
                    b.Property<Guid>("ListOfDocumentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ListCreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ListOfDocumentsId");

                    b.ToTable("ListOfDocuments");
                });

            modelBuilder.Entity("DocumentMicroservice.Entities.Document", b =>
                {
                    b.HasOne("DocumentMicroservice.Entities.ListOfDocuments", "ListOfDocuments")
                        .WithMany("documentsInList")
                        .HasForeignKey("ListOfDocumentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListOfDocuments");
                });

            modelBuilder.Entity("DocumentMicroservice.Entities.ListOfDocuments", b =>
                {
                    b.Navigation("documentsInList");
                });
#pragma warning restore 612, 618
        }
    }
}
