// <auto-generated />
using System;
using AdMicroservice.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdMicroservice.Migrations
{
    [DbContext(typeof(AdContext))]
    partial class AdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdMicroservice.Entities.Ad", b =>
                {
                    b.Property<Guid>("AdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfficialListID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OfficialListNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdID");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            AdID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            AdName = "Prodaja placa kod pijace",
                            DateOfIssue = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MunicipalityName = "Čantavir",
                            OfficialListID = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            OfficialListNumber = "1/2022"
                        },
                        new
                        {
                            AdID = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            AdName = "Prodaja placa pored crkve",
                            DateOfIssue = new DateTime(2020, 11, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MunicipalityName = "Žednik",
                            OfficialListID = new Guid("32cd906d-8bab-457c-ade2-fbc4ba523029"),
                            OfficialListNumber = "2/2022"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
