// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicBiddingRegistrationMicroservice.Entities;

namespace PublicBiddingRegistrationMicroservice.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PublicBiddingRegistrationMicroservice.Entities.ApplicationForPublicBidding", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationId");

                    b.ToTable("ApplicationForPublicBidding");

                    b.HasData(
                        new
                        {
                            ApplicationId = new Guid("a4927ae1-52e0-4b8e-bcfc-9b353cb3a7e1"),
                            BuyerId = new Guid("ab91c3fc-e095-4c38-b2a6-4117de3ac0b9"),
                            PaymentId = new Guid("cf72ddaf-66ff-435c-8129-940b25ad943d")
                        });
                });

            modelBuilder.Entity("PublicBiddingRegistrationMicroservice.Entities.PaymentForApplication", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfPayment")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublicBiddingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PurposeOfPayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceNumber")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.ToTable("PaymentForApplications");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("8ac08292-9406-45cf-aff4-0c9447880779"),
                            AccountNumber = 154564,
                            DateOfPayment = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicBiddingId = new Guid("7344fd85-ab0e-4da3-9fa4-d65af38e001f"),
                            PurposeOfPayment = "Some purpose",
                            ReferenceNumber = 855464
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
