// <auto-generated />
using System;
using ComplaintMicroservice.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComplaintMicroservice.Migrations
{
    [DbContext(typeof(ComplaintContext))]
    [Migration("20220217114656_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComplaintMicroservice.Entities.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplaintStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ComplaintStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplaintTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplaintTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfDecision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ComplaintId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Action = "Public bidding does not go to the second round",
                            ComplaintStatus = "Rejected",
                            ComplaintStatusId = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            ComplaintTypeId = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f"),
                            ComplaintTypeName = "Appeal against the course of the public tender",
                            DateOfDecision = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "Explanation",
                            NumberOfDecision = "1",
                            Reason = "Reason",
                            SubmissionDate = new DateTime(2020, 11, 13, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ComplaintId = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            Action = "Public bidding does not go to the second round",
                            ComplaintStatus = "Rejected",
                            ComplaintStatusId = new Guid("32cd906d-8bab-457c-ade2-fbc4ba523029"),
                            ComplaintTypeId = new Guid("9d8bab08-f442-4297-8ab5-ddfe08e335f3"),
                            ComplaintTypeName = "Appeal against the Decision on Leasing",
                            DateOfDecision = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "Explanation",
                            NumberOfDecision = "2",
                            Reason = "Reason",
                            SubmissionDate = new DateTime(2020, 11, 13, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
