// <auto-generated />
using System;
using CommissionMicroservice.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommissionMicroservice.Migrations
{
    [DbContext(typeof(CommissionContext))]
    partial class CommissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CommissionMicroservice.Entities.Commission", b =>
                {
                    b.Property<Guid>("CommissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameCommission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommissionID");

                    b.ToTable("Commissions");

                    b.HasData(
                        new
                        {
                            CommissionID = new Guid("8a411c13-a195-48f7-8dbd-67596c3974c0"),
                            NameCommission = "Prva komisija"
                        },
                        new
                        {
                            CommissionID = new Guid("8a211c13-a195-48f7-8dbd-67596c3974c0"),
                            NameCommission = "Druga komisija"
                        });
                });

            modelBuilder.Entity("CommissionMicroservice.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCommission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.HasIndex("CommissionID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = new Guid("2a411c13-a196-48f7-88bd-67596c3974c3"),
                            CommissionID = new Guid("8a411c13-a195-48f7-8dbd-67596c3974c0"),
                            FirstName = "Marko",
                            LastName = "Markovic",
                            NameCommission = "Prva komisija",
                            Role = "Predsednik"
                        },
                        new
                        {
                            MemberID = new Guid("3a411c13-a196-48f7-88bd-67596c3974c2"),
                            CommissionID = new Guid("8a411c13-a195-48f7-8dbd-67596c3974c0"),
                            FirstName = "Petar",
                            LastName = "Petrovic",
                            NameCommission = "Prva komisija",
                            Role = "Clan"
                        },
                        new
                        {
                            MemberID = new Guid("4a411c13-a196-48f7-88bd-67596c3974c4"),
                            CommissionID = new Guid("8a411c13-a195-48f7-8dbd-67596c3974c0"),
                            FirstName = "Jovan",
                            LastName = "Jovanovic",
                            NameCommission = "Prva komisija",
                            Role = "Clan"
                        });
                });

            modelBuilder.Entity("CommissionMicroservice.Entities.Member", b =>
                {
                    b.HasOne("CommissionMicroservice.Entities.Commission", null)
                        .WithMany("MembersOfCommission")
                        .HasForeignKey("CommissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommissionMicroservice.Entities.Commission", b =>
                {
                    b.Navigation("MembersOfCommission");
                });
#pragma warning restore 612, 618
        }
    }
}
