// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMicroservice.Entities;

namespace UserMicroservice.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220131152407_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserMicroservice.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Email = "petrović@gmail.com",
                            FirstName = "Petar",
                            LastName = "Petrović",
                            Password = "12345",
                            UserTypeId = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f"),
                            UserTypeName = "Type1",
                            Username = "Petar123"
                        },
                        new
                        {
                            Id = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            Email = "marković@gmail.com",
                            FirstName = "Marko",
                            LastName = "Marković",
                            Password = "444",
                            UserTypeId = new Guid("9d8bab08-f442-4297-8ab5-ddfe08e335f3"),
                            UserTypeName = "Type1",
                            Username = "Marko123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
